// AUTO-GENERATED by scripts/gen_ts_types.py from backend/src/analytics_api/realtime/protocol.py.
// Do not edit by hand: change the Pydantic models and re-run the script.

export interface Alert {
  readonly id: number;
  readonly rule: string;
  readonly severity: AlertSeverity;
  readonly state: AlertState;
  readonly message: string;
  readonly value: number | null;
  readonly threshold: number;
  /** ISO 8601 timestamp (UTC) */
  readonly fired_at: string;
  /** ISO 8601 timestamp (UTC) */
  readonly resolved_at: string | null;
}

export interface AlertMessage {
  readonly type: "alert";
  readonly alert: Alert;
}

export type AlertSeverity = "info" | "warning" | "critical";

export type AlertState = "firing" | "resolved";

export type Category = "electronics" | "fashion" | "home" | "beauty" | "grocery" | "sports" | "books" | "toys";

export type EventType = "order_placed" | "order_paid" | "order_shipped" | "order_cancelled";

export interface EventsMessage {
  readonly type: "events";
  readonly items: FeedEvent[];
}

export interface FeedEvent {
  /** UUID */
  readonly event_id: string;
  /** UUID */
  readonly order_id: string;
  readonly event_type: EventType;
  /** ISO 8601 timestamp (UTC) */
  readonly occurred_at: string;
  readonly amount_mad: number;
  readonly category: Category;
  readonly city: string;
  readonly payment_method: PaymentMethod;
}

export interface HelloMessage {
  readonly type: "hello";
  /** ISO 8601 timestamp (UTC) */
  readonly server_time: string;
  readonly active_alerts: Alert[];
  readonly recent_events: FeedEvent[];
}

export interface Kpis {
  /** Sum of order_paid amounts */
  readonly revenue_mad: number;
  /** Count of order_placed */
  readonly orders: number;
  readonly paid_orders: number;
  readonly shipped_orders: number;
  readonly cancelled_orders: number;
  /** revenue / paid orders */
  readonly average_order_value_mad: number | null;
  /** cancelled / placed, 0..1 */
  readonly cancellation_rate: number | null;
}

export type PaymentMethod = "card" | "cash_on_delivery" | "bank_transfer" | "wallet";

export interface PingMessage {
  readonly type: "ping";
  /** ISO 8601 timestamp (UTC) */
  readonly server_time: string;
}

export interface PipelineHealth {
  /** Accepted events/s over the last 10 s */
  readonly events_per_second: number;
  /** rejected / received in the window */
  readonly dead_letter_rate: number | null;
  /** Server time minus occurred_at of the newest committed event */
  readonly freshness_lag_ms: number | null;
  readonly queued_events: number;
  readonly connected_clients: number;
}

export interface RankedItem {
  readonly name: string;
  readonly revenue_mad: number;
  readonly orders: number;
}

export interface SeriesPoint {
  /** ISO 8601 timestamp (UTC) */
  readonly bucket: string;
  readonly revenue_mad: number;
  readonly orders: number;
  readonly cancelled: number;
}

export interface SnapshotMessage {
  readonly type: "snapshot";
  /** ISO 8601 timestamp (UTC) */
  readonly generated_at: string;
  /** Every event with seq <= this is included */
  readonly through_seq: number;
  readonly window_minutes: number;
  readonly kpis: Kpis;
  /** Same metrics for the window before this one */
  readonly previous_kpis: Kpis;
  readonly revenue_per_minute: SeriesPoint[];
  readonly revenue_per_hour: SeriesPoint[];
  readonly orders_by_status: StatusCount[];
  readonly top_categories: RankedItem[];
  readonly top_cities: RankedItem[];
  readonly payment_methods: RankedItem[];
  readonly pipeline: PipelineHealth;
}

export interface StatusCount {
  readonly status: EventType;
  readonly count: number;
}

/** Every message the server can send on /ws/live, discriminated by `type`. */
export type ServerMessage = HelloMessage | SnapshotMessage | EventsMessage | AlertMessage | PingMessage;

export type ServerMessageType = ServerMessage["type"];
