"""Generate TypeScript types for the WebSocket protocol from the Pydantic models.

The backend's Pydantic models are the single source of truth. This script exports their
JSON Schema and renders it as TypeScript, so the React, Angular and React Native apps
compile against exactly what the server sends. CI runs it with ``--check`` and fails if the
committed file is out of date.

    uv run python scripts/gen_ts_types.py          # write the file
    uv run python scripts/gen_ts_types.py --check  # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from analytics_api.realtime.protocol import ServerMessage

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontends" / "shared" / "src" / "protocol.ts"

Schema = dict[str, Any]


def _wrap(ts: str) -> str:
    return f"({ts})" if " | " in ts else ts


def ts_type(schema: Schema) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            return " | ".join(ts_type(option) for option in schema[key])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"{_wrap(ts_type(schema['items']))}[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        return (
            f"Record<string, {ts_type(extra)}>"
            if isinstance(extra, dict)
            else "Record<string, unknown>"
        )
    raise ValueError(f"unsupported schema fragment: {schema}")


_FORMAT_NOTES = {"date-time": "ISO 8601 timestamp (UTC)", "uuid": "UUID"}


def _doc(schema: Schema) -> str | None:
    parts = [schema.get("description")]
    for option in [schema, *schema.get("anyOf", [])]:
        if option.get("format") in _FORMAT_NOTES:
            parts.append(_FORMAT_NOTES[option["format"]])
    text = ". ".join(p for p in parts if p)
    return text or None


def render_definition(name: str, schema: Schema) -> str:
    if "enum" in schema:
        return f"export type {name} = {ts_type(schema)};"
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop, prop_schema in schema.get("properties", {}).items():
        doc = _doc(prop_schema)
        if doc:
            lines.append(f"  /** {doc} */")
        optional = "" if prop in required else "?"
        lines.append(f"  readonly {prop}{optional}: {ts_type(prop_schema)};")
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    schema = TypeAdapter(ServerMessage).json_schema(mode="serialization")
    definitions: dict[str, Schema] = schema["$defs"]
    union = " | ".join(ts_type(option) for option in schema["oneOf"])
    blocks = [
        "// AUTO-GENERATED by scripts/gen_ts_types.py from "
        "backend/src/analytics_api/realtime/protocol.py.",
        "// Do not edit by hand: change the Pydantic models and re-run the script.",
        "",
        *(render_definition(name, definitions[name]) + "\n" for name in sorted(definitions)),
        "/** Every message the server can send on /ws/live, discriminated by `type`. */",
        f"export type ServerMessage = {union};",
        "",
        'export type ServerMessageType = ServerMessage["type"];',
        "",
    ]
    return "\n".join(blocks)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run scripts/gen_ts_types.py")
            return 1
        print("protocol.ts is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
